type: container
title: Samba
name: samba
description: Since 1992, Samba has provided secure, stable and fast file and print services for all clients using the SMB/CIFS protocol, such as all versions of DOS and Windows, OS/2, Linux and many others.
categories:
  - Files
platform: linux
note: "Open with \\\\IP\\yacht ,Iamges: https://hub.docker.com/r/dperson/samba"
